services:
  - type: web
    name: zoyd-backend
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: node server/realtime-server.mjs
    envVars:
      - key: NODE_ENV
        value: production
